pages/errors/[id].js
The response is already sorted https://github.com/application-research/estuary/commit/2eba4e25cc03203f21024bf196ddf7fe22656697
=> Data logs for errors are already sorted

pages/comparisons-web3.tsx, pages/comparisons.tsx, pages/index.tsx, pages/verify-cid.tsx
=> Updated total files to show zero when state.totalFiles is undefined

components/RetrievalCommands.tsx
follow up to https://github.com/application-research/estuary-www/pull/18#issuecomment-978942965
=> move filc to the front of the retrieval UI

common/constants.ts
I've had this patch locally in my git stash for a few months, and decided to just send it as a pull request. LMK what you think :)
=> default to local estuary in dev mode

pages/api-admin.tsx
Simple addition of `Copy to clipboard` on the API key page.
- https://github.com/application-research/estuary-www/issues/31
=> feat: simple copy to clipboard change

pages/api-admin.tsx, pages/sign-in.tsx
Simply validate the API key on the frontend
- https://github.com/application-research/estuary-www/issues/16
https://user-images.githubusercontent.com/4479171/166695395-65ab9f02-aeba-4ee5-8e6f-c1fa03e79273.mov
=> feat: Sign in validation

package.json
Added `dev-docker` build target
=> chore: added local-docker script

README.md
Simple PR to add troubleshooting and contribution guide
=> chore: readme updates to add troubleshooting and contribution guide

components/UploadItem.tsx
Currently, non 200 HTTP response during upload is not handled. This PR will make sure we alert when an upload fails with a non 200 error
=> handle http error during upload

pages/comparisons-web3.tsx, pages/comparisons.tsx, pages/index.tsx, pages/verify-cid.tsx
Simple change to fix the total files stored display
=> chore: fixed to use totalFilesStored instead

package.json
I've updated the following modules
* `next` `12.2.4`
* `sass` `1.54.3`
please let me know if you have any questions.
=> updated version for next

pages/ecosystem.tsx
It's supposed to look like this:
=> @corinne antonia/add gitopia logo

pages/ecosystem.tsx
=> patch: added hash axis logo

pages/admin/invites.tsx
Fixed an error created by https://github.com/application-research/estuary-www/pull/70 that prevents the project from building
=> Fixed error on build due to Type Error in invites.tsx

pages/index.tsx
The word "repair" implies that there is an active process working on the data to fix it and estuary "just" restores the missing CID from filecoin network intact.
=> Reword service description

common/constants.ts, common/requests.ts, pages/ecosystem.tsx
Quick environment cost stats. Stats in USD and gets all the equinix server usage via https://metrics-api.estuary.tech
Computation is based on the usage date between the current date and 30 days prior. 
**Example: Current date: Nov 15, 2022. Usage computation is based on Oct 14, 2022 to Nov 15, 2022.**
https://user-images.githubusercontent.com/4479171/202044502-0c93cde3-4691-4c5a-9540-6cc5727496eb.mp4
=> feat: added environment cost stats

pages/ecosystem.tsx
Added AR server to the cost stats
=> feat: added AR server

pages/errors/[id].tsx, pages/providers/errors/[id].tsx
Related https://github.com/application-research/estuary/pull/534 
Updates the UI to display the Deal UUID along with error messages
=> feat: add DealUUID to error pages

components/FilesTable.tsx, pages/files-table.module.scss
Ui Fixes for the files table
- Changed the sort Icons
- Fixed Mobile Scaling
- Created a dropdown to choose a gateway
=> Files Table UI Improvements

pages/files-table.module.scss
Css fixes per https://github.com/application-research/estuary-www/pull/102#pullrequestreview-1187222235
=> CSS fixes for #102

components/FilesTable.tsx
=> Add saturn gateway option to files table

components/FilesTable.tsx
closes https://github.com/application-research/estuary-www/issues/122
=> make file names clickable

components/ResponsiveNavbar.module.scss, pages/ecosystem.tsx, pages/index.module.scss
This PR fixes the alignment in the performance page
=> Fixed alignments in performance page

components/FilesTable.tsx
Addresses https://filecoinproject.slack.com/archives/C016APFREQK/p1671110132518029?thread_ts=1671097233.969249&cid=C016APFREQK
before
after
=> Use cid as name if undefined

pages/ecosystem.tsx
Added shuttle-5 uuid on the cost section of ecosystem page.
=> chore: added shuttle-5 uuid on the cost section of ecosystem page

pages/ecosystem.tsx
- added nsq and the new db servers
=> chore: added ecosystem uuids

components/Card.module.scss, components/Footer.module.scss, components/Hero.module.scss, components/Hero.tsx, components/ResponsiveNavbar.module.scss, components/ResponsiveNavbar.tsx, pages/ecosystem.tsx, pages/index.module.scss, pages/index.tsx
Added a simple header to the performance page and prettified previous CSS files.
=> Added header component

pages/home.tsx, pages/upload-cid.tsx, pages/upload.tsx
small tweaks to the following widgets:
**(added upload button and some text blurb about what this page is)**
**(upload manually => upload a file instead)**
=> Clarify upload language, add upload link to files page

pages/ecosystem.tsx, pages/index.tsx
added ClubNFT and Encloud to ecosystem page and homepage
=> added encloud and clubnft logos
