application-research/estuary-www

common/useFissionAuth.ts, global.scss, package.json, pages/account-setup.tsx, pages/authed-with-fission.tsx, pages/settings.tsx, pages/sign-in.tsx, pages/sign-up.tsx
This pull request adds Fission auth alongisde the current Estuary auth system.  The new authentication system leverages the current API key system.
We should probably treat this PR as a draft because more work is needed before it add value.
The summary outline describes how authentication with Fission works as currently implemented in this PR.
**Sign Up**
- User does not have a Fission account
+ Redirect to Fission Auth Lobby where they grant permission to use their storage and the fil-cosigner key
+ Redirect back to a new interstitial "Account Setup" page
+ User signs up as usual with username, password, and invite code (maybe we can not require a password here?)
+ Two tokens are requested
- One that is set as a cookie in the usual way
- A second one is stored in WNFS for the next time …
=> Add Fission auth

pages/your-miners.tsx
Discovered while trying to rename the miner i just added and took control of. I think the only problem here is the URL is based on the address rather than the name. Based on the other URL's used, I believe this is what's needed.
=> Fix miner rename button

components/Navigation.tsx
Given the `verify-cid` URI is dependent on the root domain, it's best to change it to a relative path. This will make it easy for testings this endpoint irrespective of the application environment (dev/prod). Right now, if you run this application on your dev machine, the `verify-cid` points to the prod link (which is not useful given CID generated locally to the best of my knowledge, will not be verified)
=> Use relative path for verify-cid href

pages/verify-cid.tsx
When CID is verified, we should check the length of the deals is more than 0. The response from the API to verify a CID always sends a deals field, so checking if it exists is not enough. This fix will stop the UI from misleading users when they actually haven't made any deals for a CID.
Before this fix
After this fix
This closes https://github.com/application-research/estuary-www/issues/30
=> Bug: Properly check deal exist on chain when verifying CID

pages/staging.tsx
The staging bucket `size` on the UI does not currently display in the storage unit (`GiB`) like the staging min/max sizes. This PR will make sure the unit is properly displayed and make it intuitive for users to understand where they are on how much data is staged vs the requirements.
The UI before this fix
The UI after this fix
=> display bucket size in storage unit

pages/deals/index.tsx
Currently, the deals UI uses the settings replication and not the content replication. The content replication is the granular replication value used to maintain deals count. This PR will fix it to use the actual content replication. 
I noticed this bug when I change replication count when running estuary, I expected the different contents to have their replication counts maintained depending on the `--replication` flag or the `replication` param when the content is created - they did not, the UI kept showing the default instead of the content replication.
Before the fix - this content has a replication of 2 but kept showing 6;
After the fix - UI is now showing the right replication count - 2
=> use content replication over settings replication on deals UI

pages/home.tsx, pages/upload-cid.tsx
The change in the `Content` field would force us to rebuild the `contents` table and given that this field mapping is just for naming convenience (using filename instead of name) without any major functionality introduced, we should revert and just use the same field name. 
This PR reverts all the changes we did to rename the `name` field to `filename`.
https://github.com/application-research/estuary/pull/389
=> chore: revert filename change

pages/ecosystem.tsx
- I removed logos for both nft.storage and web3.storage
=> patch: remove 2 logos

pages/admin/balance.tsx
Trying to fix this error. 
After datacap is exhausted we get verifiedClientBalance as null from the balance API.
=> fix: null case of verifiedClientBalance in balance page

pages/admin/invites.tsx
Added a copy button to the estuary invites table to make it easier to copy and send out estuary invites.
=> Added a Copy button to the estuary invites table

pages/admin/invites.tsx
Added logic to generate invite links differently if the project is running on localhost. 
Local host invite links now use this format:
`http://${window.location.host}/sign-up?invite=${data.code}`
=> Fixed estuary invite links on localhost

pages/sign-in.tsx
I noticed that the sign-in page from cli-auth was committed along with the webmint PR https://github.com/application-research/estuary-www/pull/68. As per our discussion, this shouldn't be included for now pending any further discussion on how to improve the use of salt on the frontend.
=> chore: reverted the cli-auth changes

pages/admin/balance.tsx
**Problem**: When setting up a new estuary node, you can’t find your FIL address through the estuary-www UI because the /admin/balance endpoint fails until the address has a balance. This creates friction if you miss the FIL address in the CLI output, creating friction in getting your account funded.
**Proposed Solution**: Use a dedicated /admin/fil-address endpoint so we can always display the FIL address in the Balance page. (PR to add endpoint: https://github.com/application-research/estuary/pull/476)
**Note**: Safe to merge regardless of timing with https://github.com/application-research/estuary/pull/476 (console will see a 404 if merged out of order), but functionality is dependent on that PR.
=> Show FIL address in Balance page even before account has a balance

components/FilesTable.tsx
Discovered this bug during my test of the new API endpoint. We only need to generate the retrieval link for non-aggregated CIDs.
We need this fix as part of 0.1.10 release. Any users with aggregated CID will see a blank page if we don't have this.
=> chore: generate retrieval links for non-aggregate cids

common/requests.ts
Key mgmt APIs were hardcoded to hit api.estuary.tech which prevented key mgmt page from working on localhost in dev mode. This also leads to excess 401s on our prod API.
=> Use context api host instead of prod api for key mgmt

common/utilities.ts, components/FilesTable.tsx, components/UploadItem.tsx, pages/admin/content.tsx, pages/deals/[id].tsx, pages/deals/index.tsx, pages/proposals/[cid].tsx, pages/receipts/[id].tsx, pages/staging.tsx, pages/upload-cid.tsx, pages/verify-cid.tsx
~Replaces any link that is intended to point to estuary-hosted content with the estuary gw instead of dweb.~ **Shows both gateway links throughout the UI, labeled as "Estuary retrieval url" and "Dweb retrieval url".** The estuary gw defers to dweb if the cid is not actively pinned by estuary or has been offloaded, so it is safe to point to the estuary gw as long as estuary API nodes are up. Dweb is still provided as a back up option until we decide to only show the estuary url. 
Note: For pinned directory nodes, users will get a much faster response on average through the estuary url but a much less dressed-up gateway UI, until we update our gateway rendering. 
- https://api.estuary.tech/gw/ipfs/bafybeidj7c2e3daplalccukbps4eze7473gyshspev76xi4sjfmfkuaofe/
- …
=> Show both estuary and dweb retrieval urls

pages/staging.tsx
1. Removes closing time concept from staging bucket, as per https://github.com/application-research/estuary/pull/535.
2. Adds bucket item count
3. More intuitive ordering of how these stats are shown (curr on left half, limits on right half).
Note: if we merge https://github.com/application-research/estuary/pull/535 then the only readiness reason will be not being in the right storage size range.
=> Re-org staging zone view for readiness simplification

pages/verify-cid.tsx
The verify page shows content ID instead of CID
before
after
=> fix gateway url on verify-cid page

pages/errors/[id].tsx, pages/providers/errors/[id].tsx
Increased width of the Deal UUID column so uuids don't get truncated. 
Before, it looked like this:
Now it looks like this:
=> fix: increase column width

pages/staging.tsx
maxItems concept was removed in https://github.com/application-research/estuary/pull/535, should stop trying to render it
=> Re-org staging zone layout again to remove maxItems concept

components/CreateKeyModalBody.tsx, pages/api-admin.tsx
Fixes perm keys being auto-created with no label and never showing the actual key in the UI. Now, the behavior matches the flow for regular keys.
Also adds in the language that we don't store api keys.
=> Also show label dialog for permanent keys

pages/comparisons-web3.tsx, pages/comparisons.tsx, pages/ecosystem.tsx, pages/index.tsx, pages/verify-cid.tsx
- use metrics api to get the stats on ecosystem dev page
Metrics api uses the same data source but the endpoints (web services) are hosted on a different HA server using render.com
Here's the swagger endpoint
https://metrics-api.onrender.com/swagger/index.html#/Stats/get_stats_info
=> fix: use metrics api on ecosystem dev page for stats

pages/comparisons-web3.tsx, pages/comparisons.tsx, pages/ecosystem.tsx, pages/index.tsx
- use stats/deal-metrics from metrics api to replace the /deals-on-chain endpoint
=> feat: use metrics api deal-on-chain endpoint

components/FilesTable.tsx, components/StagingZoneReadinessTable.tsx, pages/files-table.module.scss, pages/home.tsx
1. https://github.com/application-research/estuary/pull/631 removed aggregate rows from /content/stats, so the Files column becomes irrelevant and is removed in this PR
2. Size and createdAt were added to the /content/stats response data, and is rendered in this PR
3. some col width tuning
To be released after estuary 0.2.1.
before:
after:
=> Remove files col + Show size and created at in files table

pages/verify-cid.tsx
closes #128 
Now error messages are displayed on the UI when returned from the `verify cid` endpoint
=> fix: update verify-cid page to display errors

components/FilesTable.tsx, components/PinStatusIcon.module.scss, components/PinStatusIcon.tsx, package.json, pages/files-table.module.scss, pages/home.tsx, pages/index.module.scss
blocked on https://github.com/application-research/estuary/pull/772
add icons with tooltips for each pinning statuses (demonstrated in order in screenshot):
- queued
- pinning
- pinned
- failed
- offloaded
Note: the statuses in the above screenshot are manufactured, it will typically look more like below (with healthy estuary)
=> Render pinning status icon in contents tables

package.json
This reverts commit 6f8b2c6c2dc0ccaf76d033a4a2b14c9de31bae79.
Turns out these libs are needed by material ui to build. See failed render build without them: https://dashboard.render.com/web/srv-c249sqjs1ghc004rv0n0/deploys/dep-ced5jocgqg45ht8b60og
=> Revert "Remove unused @emotion dep"

package.json
When setting the `ESTUARY_API` environment variable it was not being set on the code. This fixes it.
=> Fix environment variables not set

pages/index.tsx
Added a small error message at the bottom of the homepage paragraph for when total pinned CIDs and storage deals fail to load and hid the sentences with "0" numbers for when that error happens.
=> Added small error message when CIDs and total deals fail to load

.prettierrc, components/ProgressBar.module.scss, components/ProgressBar.tsx, global.scss, pages/ecosystem.tsx
Added success and failure rate on ecosystem page.
@APiligrim will modify the section based on our branding / design preference.
=> feat: add success / fail rates

pages/ecosystem.tsx
This pr fixes an operator error on the performance page. With the `null` instead of `undefined` it will display the Deal rate once the rate is loaded and is not null.
=> Fix error on performance page

pages/ecosystem.tsx, pages/index.tsx
this pr multiplies the total number of objects by 6 because we have over 50 million total root CIDs yet each of the CIDs gets copied 6 times to make sure that the data is permanently available.
=> Multiplied total number of objects by 6

common/constants.ts, components/Footer.module.scss, components/Hero.module.scss, components/ProgressBar.module.scss, components/ProgressBar.tsx, components/icons/DealsIcon.tsx, components/icons/ErrorIcon.tsx, components/icons/SignalIcon.tsx, components/icons/UserCheckedIcon.tsx, global.scss, pages/StorageProvidersTable.module.scss, pages/StorageProvidersTable.tsx, pages/ecosystem.tsx, pages/index.module.scss, pages/providers/stats/[id].tsx
This pr updates the SP table so that people can see the number of sorted deals each provider makes without having to click on them separately. 
Is it useful to display the `Error Count` or should we display the amount of storage each SP stores? I couldn't find that information 👀 
Also added the same gradient to the footer and progress bar as the header
=> Update Storage Provider table

common/server.ts
Deleting API keys is currently throwing a CORS error on prod due to DELETE missing. Also adding PUT since we have API endpoints that use it, like password changing.
Note: Token hash referenced in the image is expired, will delete after this goes through.
=> Add PUT and DELETE to cors middleware

.gitignore, components/Page.tsx, components/PlausibleAnalyticsScript.tsx
This pr adds [ Plausible analytics](https://plausible.io/) (which is a lighter version of google analytics with more data privacy) to the `head` component to track user traffic. Also adding `.env` to .gitignore 👀 
In Nextjs 13 there is a native `Script` tag which is also used on storage.market but it doesn't work in the version that we have here so I'm using a regular `script` HTML tag. Are we going to migrate estuary's codebase to Nextjs 13 once it gets more documentation/tutorials?
=> Added Plausible Analytics

components/ResponsiveNavbar.tsx
This pr removes the titles from the ecosystem page navbar since we removed the content for now
=> Removed empty titles from the Navbar

pages/api-admin.tsx, pages/sign-in.tsx
Blocked on https://github.com/application-research/estuary/pull/861
Along with https://github.com/application-research/estuary/pull/861, fixes https://github.com/application-research/estuary-www/issues/99 and https://github.com/application-research/estuary/issues/815
1. Do not render session tokens in api admin page (they should only be managed via sign in and sign out)
2. Admin login fix taken from https://github.com/application-research/estuary/issues/815#issuecomment-1364707188
3. Remove authenticate via API key since it's unnecessary now that admin login is fixed, and to prevent mixing up session and service tokens
**Warning:** if any estuary node operators have an admin user with a password that doesn't meet the 8 alphanumeric characters bcrypt requirement, they will end up getting …
=> Prevent mixing up session and service tokens, fix admin login, remove authenticate via API key
